apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-test-sa
  namespace: aws-test
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::519400893680:role/eksctl-aws-test-eks-addon-iamserviceaccount-a-Role1-uH8nf2nlvpi5
